// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgVhjrCdLbWUfJu0bIaRxGLukTv29QD5w',
    appId: '1:998386189564:web:6172f3f888adabb1770379',
    messagingSenderId: '998386189564',
    projectId: 'growtogether-16693',
    authDomain: 'growtogether-16693.firebaseapp.com',
    storageBucket: 'growtogether-16693.firebasestorage.app',
    measurementId: 'G-5GZYNY9QM1',
    databaseURL: 'https://growtogether-16693-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOort5jhL9GPjH6-HDcnL8a8pjq9bKN84',
    appId: '1:998386189564:android:1a0c58c0391a27d3770379',
    messagingSenderId: '998386189564',
    projectId: 'growtogether-16693',
    storageBucket: 'growtogether-16693.firebasestorage.app',
    databaseURL: 'https://growtogether-16693-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1KDVjnQcdUY39mLjMjMEU6hFFBlUTXw8',
    appId: '1:998386189564:ios:b335710ae355aff2770379',
    messagingSenderId: '998386189564',
    projectId: 'growtogether-16693',
    storageBucket: 'growtogether-16693.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
    databaseURL: 'https://growtogether-16693-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1KDVjnQcdUY39mLjMjMEU6hFFBlUTXw8',
    appId: '1:998386189564:ios:b335710ae355aff2770379',
    messagingSenderId: '998386189564',
    projectId: 'growtogether-16693',
    storageBucket: 'growtogether-16693.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
    databaseURL: 'https://growtogether-16693-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgVhjrCdLbWUfJu0bIaRxGLukTv29QD5w',
    appId: '1:998386189564:web:52569f254989a45c770379',
    messagingSenderId: '998386189564',
    projectId: 'growtogether-16693',
    authDomain: 'growtogether-16693.firebaseapp.com',
    storageBucket: 'growtogether-16693.firebasestorage.app',
    measurementId: 'G-98NTLZR2LQ',
    databaseURL: 'https://growtogether-16693-default-rtdb.firebaseio.com/',
  );
}